version: "3.8"
services:
  # mysql - first start can be slow, make sure the service is ready before launching the other containers
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database

  #live example with python served from the container
  python:
    depends_on: 
    - mysql
    build: ./python/
    ports:
      - 8000:8000
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: test_database
      MYSQL_PASSWORD: root

  #live example with python app served from the local file system
  python2:
    depends_on: 
    - mysql
    build: ./python/
    ports:
      - 8001:8000
    volumes:
      - ./python/:/usr/src/app
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: test_database
      MYSQL_PASSWORD: root

 
  #live example with files coming from the container
  php:
    depends_on:
    - mysql
    build: ./php/
    ports:
      - 8002:80
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: test_database
      MYSQL_PASSWORD: root

  #live example with local file access
  php2:
    depends_on:
    - mysql
    build: ./php/
    volumes:
      - ./php/:/var/www/html/
    ports:
      - 8003:80
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: test_database
      MYSQL_PASSWORD: root

